
name: 九斤

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 23,0-15 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JJRM_HD: ${{ secrets.JJRM_HD }}
        JJRM_URL: ${{ secrets.JJRM_URL }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【九斤人脉】'
        if: env.JJRM_HD
        run: |
          node Task/jjrm.js
