
name: 睡眠

on:
  workflow_dispatch:
  schedule:
     - cron: '* */4 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YGKC_HD: ${{ secrets.YGKC_HD }}
        YGKC_URL: ${{ secrets.YGKC_URL }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【睡眠】'
        if: env.YGKC_HD
        run: |
          node Task/smz.js
