name: iboxpay

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0,12 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XP_refreshTOKEN: ${{ secrets.XP_REFRESHTOKEN }}
        XP_iboxpayvideoHEADER: ${{ secrets.XP_IBOXPAYVIDEOHEADER }}
        XP_iboxpayvideoBODY: ${{ secrets.XP_IBOXPAYVIDEOBODY }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.XP_REFRESHTOKEN
        run: |
          npm install
      - name: '运行 【笑谱】'
        if: env.XP_REFRESHTOKEN
        run: |
          node Task/iboxpay.js
