name: zqshare

on:
  workflow_dispatch:
  schedule:
     - cron: '*/2 23,0-15 * * *'
  watch:
    types: started
env:
    TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
      - name: '运行 【zqshare】'
        run: |
          node Task/youthshare2.js
